version: '3.9'

services:
  app:
    build: .
    container_name: online-store-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/online-store-api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_FLYWAY_PASSWORD=1234
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    container_name: postgres_15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=online-store-api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: